---
bostonrtr1:
  hostname: bostonrtr1
  username: cisco
  password: cisco
  groups:
    - ios
  data:
    device_asn: 30
    interfaces:
      loopback123:
        state: no shut
        descr: ntp source loopback
      loopback10:
        state: no shut
        descr: primary loopback


